[package]
name = "day6"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc.workspace = true
owo-colors.workspace = true
itertools.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "benchmark"
harness = false
