[workspace]
members = [
    "aoc", "day1", "day2", "day3", "day4", "day5", "day6", "day7",
]
resolver = "3"

[workspace.dependencies]
aoc = {path = "./aoc"}
owo-colors = "4"
itertools = "0.14.0"
divan = "0.1.21"
